version: '3.8'

services:

  flask-service:
    build:
      context: ./flask-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - laravel
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: mysql:8.0.35-debian
    container_name: mysql_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'      
      MYSQL_DATABASE: storyweaver
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    restart: always

  redis:
    image: redis:6-alpine
    networks:
      - laravel
    ports:
      - "6379:6379"

networks:
  laravel:

volumes:
  mysql_data:
